# TextForensics Package Configuration

[tool.poetry]
name = "textforensics"
version = "0.1.0"
description = "GPU-optimized text forensics ML pipeline"
authors = ["Surajit Dutta <hello@surajit.de>"]
packages = [{include = "textforensics", from = "src"}]

# Code formatting with Black
[tool.black]
line-length = 88
target-version = ["py312"]

# Import sorting with isort
[tool.isort]
profile = "black"
line_length = 88

# Linting with flake8
[tool.flake8]
max-line-length = 88
ignore = "E501,F401"

# Type checking with mypy
[tool.mypy]
python_version = "3.12"
warn_return_any = true
disallow_untyped_defs = true

# Build system configuration
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
